name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v18
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Crear archivo estático index.html
        run: |
          mkdir -p public
          echo "<!DOCTYPE html>
          <html lang='es'>
          <head>
            <meta charset='UTF-8'>
            <meta name='viewport' content='width=device-width, initial-scale=1.0'>
            <title>ci-cd-webapp</title>
          </head>
          <body>
            <h1>¡Hola, mundo desde GitHub Pages!</h1>
            <p>Bienvenidos a mi aplicación desplegada usando GitHub Pages.</p>
          </body>
          </html>" > public/index.html

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
